// Code generated by command: go run aes_asm.go -pkg hash -out ../hash/aes_amd64.s -stubs ../hash/aes_amd64.go. DO NOT EDIT.

//go:build !purego
// +build !purego

package hash

func aes(s string, k *uint8) uint64
